name: 🐦 Release to Tweet

on:
  create

permissions:
  contents: read

jobs:
  tweet:
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        run: |
          tag='${{ github.event.ref }}';
          result=$(echo "$str" | sed 's/@/ /');
          echo "$result";
          message = '🤖 Ant Design Web3 just released \"$result\" ✨🎊✨ Check out the full release note: https://github.com/ant-design/ant-design-web3/releases/tag/${{ github.event.ref }}';
          echo "message";          
       
