name: 🐦 Release to Tweet

on:
  create

permissions:
  contents: read

jobs:
  tweet:
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        run: |
          str='${{ github.event.ref }}';
          result=$(echo "$str" | sed 's/@/@/');
          echo "$result";
          
       
