name: 🐦 Release to Tweet

on:
  create

permissions:
  contents: read

jobs:
  tweet:
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: nearform-actions/github-action-notify-twitter@v1
        with:
          message: |
          🤖 Ant Design Web3 just released ${{ github.event.ref }} ✨🎊✨ Check out the full release note: https://github.com/ant-design/ant-design-web3/releases/tag/${{ github.event.ref }}
          twitter-app-key: ${{ secrets.WEB3_TWITTER_API_KEY }}
          twitter-app-secret: ${{ secrets.WEB3_TWITTER_API_SECRET_KEY }}
          twitter-access-token: ${{ secrets.WEB3_TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.WEB3_TWITTER_ACCESS_TOKEN_SECRET }}
