# Current release process:
# 1. `npm run pub` will call antd-tools `run pub`
# 2. antd-tools `run pub` will generate a new tag
# 3. antd-tools `run pub` will trigger `npm publish` at the same time
# 4. Then the new tag will trigger this current action
# 5. The action will generate a new release, and publish DingDing notification at the same time

name: DingTalk Release Notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-helper:
    permissions:
      contents: write  # for actions-cool/release-helper to create releases
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Send to Ant Design Web3 DingGroup
        uses: actions-cool/release-helper@v2
        with:
          trigger: 'tag'
          branch: 'master'
          dingding-token: ${{ secrets.WEB3_DINGDING_BOT_TOKEN }} 
          msg-title: '{{v}} 发布日志'
          msg-poster: 'https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*zx7LTI_ECSAAAAAAAAAAAABkARQnAQ'
          msg-footer: '💬 前往 [**Ant Design Web3 Releases**]({{url}}) 查看更新日志  🐦 twitter: https://twitter.com/AntDesignWeb3'
          prettier: true
          prerelease-notice: true
          prerelease-filter: '-, a, b, A, B'
