name: test-hello2-master

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: thinkasany/organize-contributors@master
        with:
          organize_name: 'hellof2e'
          github_token: ${{ secrets.GH_TOKEN }}
          png_path: images-hello2/contributors.png
          json_path: json-hello2/data.json
          branch: 'dev' # 不配置默认master分支
          committer_name: 'think-hello-bot' # 不配置默认contributors bot
          committer_email: 'thinkasany@163.com' # 不配置默认action@gmail.com
          commit_message: 'chore: 测试新的没有的目录' # 不配置默认chore: update contributors [skip ci]